version: '2'
networks: 
  dev: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
services: 
  gateway:
    image: u03013112/ss-gateway
    container_name: 'gateway'
    tty: true
    # restart: always
    ports:
      - 18021:8081
    networks:
      - dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  tester:
    image: u03013112/ss-tester
    container_name: 'tester'
    # restart: always
    depends_on: 
      - mysql
    tty: true
    command: /usr/local/bin/ss-tester tester
    networks:
      - dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  spider:
    image: u03013112/ss-tester
    container_name: 'tester'
    # restart: always
    depends_on: 
      - mysql
    tty: true
    command: /usr/local/bin/ss-tester spider
    networks:
      - dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  mysql:
    image: mysql:5
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - .data/mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    container_name: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=!@#sspaas@U0
      - MYSQL_DATABASE=ss_main
    # restart: always
    ports:
      - 127.0.0.1:3306:3306
    networks: 
      - dev